### ISSUE TITLE
(myengine0) Failed to decode dnsmasq lease status: unexpected end of JSON input

### ISSUE THREAD

**Issue by keithwbacon** [dhiltgen/docker-machine-kvm#10]
docker version 1.9.1
docker-machine 0.5.6 and 0.6.0+

docker-machine create -d lvm myengine0

NAME        ACTIVE   URL   STATE     URL   SWARM   DOCKER    ERRORS
myengine0   *        kvm   Running                 Unknown   unexpected end of JSON input

docker-machine ls

NAME        ACTIVE   URL   STATE     URL                        SWARM   DOCKER    ERRORS
myengine0   -        kvm   Running   tcp://192.168.42.44:2376           Unknown   Unable to query docker version: Unable to read TLS config: open /root/.docker/machine/machines/myengine0/server.pem: no such file or directory

Thoughts?

**Comment by dhiltgen** [comment]
Are you running as root or your user account?  If so, maybe there's something strange set in your environment leading it to try to store/access certs in ~root

I generally try to run it as myself with my account added to the various groups required to access libvirt/qemu.

**Comment by dhiltgen** [comment]
Although that may just be a ghost of the first failure.  You might want to try running the create with Debug.

`docker-machine -D create -d kvm myengine1`

**Comment by keithwbacon** [comment]
Thanks for your suggestions.  I used my user account and waited longer, after 24 tries it worked!
I was not patient enough.  I retested as root and using docker-machine 0.6.0 released earlier today and all works as well.  The key - wait 24 retries.

(myengine2) Failed to decode dnsmasq lease status: unexpected end of JSON input
(myengine2) DBG | Unable to locate IP address for MAC _______________
(myengine2) DBG | Waiting for the VM to come up... 24
(myengine2) DBG | GetIP called for myengine2
(myengine2) DBG | IP address: 192.168.42.75
(myengine2) DBG | Unable to locate IP address for MAC ______________

**Comment by dhiltgen** [comment]
I do need to quiet down the repeating message.  That used to get swallowed, but now shows up in more recent machine builds and leads to confusion.  (it takes a while for the VM to start up so I can get the IP address)

**Comment by keithwbacon** [comment]
The test I was performing was mac host with vmware with linux guest with kvm.  Now I can drop this on a linux box

**Comment by keithwbacon** [comment]
I saw your fast update - thanks working great!  Tested with docker 1.10 and machine 0.6.0
