### ISSUE TITLE
Please include a LICENSE

### ISSUE THREAD

**Issue by dlorenc** [dhiltgen/docker-machine-kvm#17]
Hey,

I'd like to submit some PRs to this repo, but my employer requires that you have a LICENSE defined. Would you mind choosing one and including it in the root of the repo?

**Comment by dlorenc** [comment]
Friendly ping @dhiltgen. Any chance you could add a LICENSE to this code?

**Comment by dhiltgen** [comment]
This is heavily based on the docker/machine project, so it's the same - https://github.com/docker/machine/blob/master/LICENSE

**Comment by dlorenc** [comment]
Thanks for confirming! Would you mind if I send a PR adding that, to make it explicit?

**Comment by dhiltgen** [comment]
Fixed in https://github.com/dhiltgen/docker-machine-kvm/commit/e302cd8ff7af3fbd4d33f6780f632d11798d21c1
