### ISSUE TITLE
Error to load plugin with 0.0.5

### ISSUE THREAD

**Issue by atoy40** [dhiltgen/docker-machine-kvm#4]
Hello, i've diownloaded your 0.0.5 release and have tried to test it with d-m 0.0.5 but i get :

$ docker-machine create --driver kvm --help
Error loading driver "kvm": dial tcp: missing address

Any idea ?

Thanks
Anthony.

**Comment by zhangchl007** [comment]
I got the same issue:
Error loading driver "kvm": dial tcp: missing address
[root@oc3053148748 bin]# ls -l *kvm*
-rwxr-xr-x. 1 root root 12242688 Nov 25 17:11 docker-machine-driver-kvm
[root@oc3053148748 bin]# docker-machine create --driver kvm  --help
Error loading driver "kvm": dial tcp: missing address

**Comment by atoy40** [comment]
After some test, I launch directly te plugin binary file docker-machine-driver-kvm and it generate a core dump.
So i recompile it and now the binary is working, but give me a different error :

$ docker-machine create --driver kvm --help
WARNING >>> Error attempting heartbeat call to plugin server: rpc: can't find service RpcServerDriver.Heartbeat
Error loading driver "kvm": rpc: can't find service RpcServerDriver.GetVersion

Anthony.

**Comment by adrahon** [comment]
The last error message is because of a change in the machine plugin code AFAIK https://github.com/docker/machine/issues/2325

The plugin should still work with machine 5.0

**Comment by adrahon** [comment]
Simply rebulding the plugin against the latest machine version works for me.

**Comment by dhiltgen** [comment]
I've just pushed a new tag/binary for 0.5.6.
